### ISSUE TITLE
Siren?

### ISSUE THREAD

**Issue by macinspak** [homebridge-plugins/node-arlo#10]
Hey, I am using node-red-contrib-arlo which I uses this library.

I wrote https://flows.nodered.org/node/node-red-contrib-alarm which acts as a node-red powered alarm panel. You hook up various sensors to it and sirens and it is your alarm panel. Hue Motion Sensors, zwave door sensors, arlo camera motion, etc can all act as sensors.

I would like to see if I can use the siren in the Arlo base station as the siren for the node-red powered alarm system.

This golang library provides SirenOn/SirenOff commands, so it shouldn't be too hard to figure out how:
https://github.com/jeffreydwalter/arlo/wiki/API-Documentation

Really, I would like to basically trigger an "entrance delay" style "pip, pip" alert and then a full blown internal siren, or just an internal siren if that's the best we can do. But surely they have a warning mode as well as a full blast?

Thoughts?

**Comment by macinspak** [comment]
Linked to https://github.com/HendrikRoth/node-red-contrib-arlo/issues/5

**Comment by jensrossbach** [comment]
I agree, please add possibility to switch on/off the siren of the Arlo base station, thanks!
