### ISSUE TITLE
Example code for Motion-Events

### ISSUE THREAD

**Issue by HendrikRoth** [homebridge-plugins/node-arlo#3]
Hello,
could you please provide a simple example for listening for motion events?

I tried to listen on 'statusUpdate', but this did not work. Thank you!

**Comment by HendrikRoth** [comment]
Tried it this way:
```js
var device = self.config.arlo.devices[n.device]

  device.subscribe(function(error, response) {
    if (error) {
     console.log(error)
   }
   response.on('statusUpdate', function(msg) {
     console.log(msg)
   })
  }
```

**Comment by adam-lynch** [comment]
@HendrikRoth any luck?

**Comment by HendrikRoth** [comment]
No :(

I am able to enable/disable the cameras, but still have no idea how to listen to motion events.

https://github.com/HendrikRoth/node-red-contrib-arlo

**Comment by adam-lynch** [comment]
I found a way to figure out when motion is detected. In the `found` event (callback), there's something like `device._____lastImage` or `device.device.______lastImage` (per camera). Request that S3 image URL and save the `last-modified` header from the response. Every N seconds, request it again and if the `last-modified` has changed, that camera has detected motion.

**Comment by devbobo** [comment]
Sorry, I haven't had the bandwidth to look at this issue until now.

I've just pushed version `0.0.3` which adds support for motion events.

```javascript
var device = self.config.arlo.devices[n.device];

device.on('motion', function(state) {
  //state is true for motion detected, false for no motion
});
```

**Comment by HendrikRoth** [comment]
Thank you, will look at it at the weekend!
For listening on state changes (arm/disarm), we have to listen on the basestation, or? i did not see any committed event for this.

**Comment by devbobo** [comment]
You should be able to listen for those events like this...

```javascript
basestation.on(Arlo.ARMED, function() {
  //todo
});

basestation.on(Arlo.DISARMED, function() {
  //todo
});
```

**Comment by devbobo** [comment]
I should also note that `Arlo.DISARMED` and `Arlo.ARMED` listening for  `mode0` and `mode1` the default modes that are created when you register your Arlo basestation.

If you create additional custom modes, they take the names `mode2`, `mode3`, etc. You can subscribe to these custom modes using...

```javascript
basestation.on('mode2', function() {
  //todo
});
```

**Comment by HendrikRoth** [comment]
perfect, thank you for the hint. i have now the listening and the triggering part finished for arlo states. just need to look for the motion events at the weekend. thanks!

**Comment by ajcooper72** [comment]
Sorry for jumping on this thread but having trouble getting events from working in my script.  Here's the code;

```
arlo.login(ARLO_USERNAME, ARLO_PASSWORD, function () {
    arlo.getDevices(function () {
        for (let device in arlo.devices) {

            if (arlo.devices[device].device.deviceType == "basestation") {
                var basestation = arlo.devices[device];
                basestation.on(Arlo.ARMED, function () {
                    console.log("armed");
                });
        
                basestation.on(Arlo.DISARMED, function () {
                    console.log("disarmed");
                });
            }

            if (arlo.devices[device].device.deviceType == "camera") {
                var camera = arlo.devices[device];
                camera.on('motionDetected', function (state) {
                    //state is true for motion detected, false for no motion
                    console.log("motion");
                });
            }
        }
    })
})
```

It's logging in, finding the devices (I've tested outputting the ID's) but none of the events are triggering.

For reference, node -v is showing v8.11.1.

Any pointers would be appreciated.
