### ISSUE TITLE
Missing support for non-mfa enabled accounts

### ISSUE THREAD

**Issue by bigluck** [homebridge-plugins/node-arlo#71]
**Is your feature request related to a problem? Please describe.**
First thing first: great job!
I'm trying to use this plugin for a personal project but it looks like accounts without MFA are not supported yet!

**Describe the solution you'd like**
I'd like to just provide the `arloUser` and `arloPassword` properties.

**Additional context**
For these accounts, when the `_getAuthToken()` is invoked, arlo will return this response:

```
{
  _type: 'AccessTokenV2',
  token: '...mytoken...',
  userId: '...myuserid...',
  authenticated: 1644240464,
  issued: 1644240464,
  expiresIn: 1645536464,
  mfa: false,
  authCompleted: true,
  type: 'USER',
  MFA_State: 'ENABLED'
}
```

When `mfa = false` the library should just skip the MFA validation and return true to the `login()` method.

**Comment by easton36** [comment]
Idk if you guys allow this, but I rebuilt the whole library with MFA support
https://github.com/easton36/arlo.js
